apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-ws
  template:
    metadata:
      labels:
        app: game-ws
    spec:
      containers:
      - name: game-ws
        image: contardorm/desafio-ws:latest
        imagePullPolicy: Always 
        resources:
          limits:
            cpu: 1
            memory: 500Mi
        ports:
        - containerPort: 8080
      automountServiceAccountToken: false
