# templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flask
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: 1
              memory: 500Mi
        automountServiceAccountToken: false
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: FLASK_HOST
              value: "{{ .Values.flaskHost }}"  # Utilizar la variable de entorno definida en values.yaml
            - name: FLASK_PORT
              value: "{{ .Values.flaskPort }}"  # Utilizar la variable de entorno definida en values.yaml
