name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/game-ws:latest .
          docker images 

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/game-ws:latest

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          docker run \
            --rm \
            -e SONAR_HOST_URL="https://sonarcloud.io" \
            -e SONAR_LOGIN="${{ secrets.SONAR_TOKEN }}" \
            -v "$(pwd):/usr/src" \
            sonarsource/sonar-scanner-cli

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
          version: '1.21.0'

#      - name: Run kubectl apply
#        run: |
#          kubectl apply -f k8s/
#          kubectl get po

      - name: Download Helm script
        run: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3

      - name: Install Helm
        run: bash get_helm.sh

      - name: Deploy with Helm
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          kubectl version --client
          helm version
          helm repo add stable https://charts.helm.sh/stable
          helm repo update
          helm upgrade --install game-ws ./k8s/helm
          kubectl get po
          helm ls
